### ISSUE TITLE
Full set of posterior draws

### ISSUE THREAD

**Issue by wetlandscapes** [maquinolopez/Plum#2]
Hi,
Thanks for putting this set of functions together. With just a little bit of tweaking I was able to get the package running on Windows Subsystem for Linux (using X11 forwarding via Xming Server).

I'm looking through the results of `runPlum()` and notice that the ages.csv contains posterior information for specified depths, but that these data are only a synthesis of the full data set. I'm curious if there is a way to:
1. Get the complete set of posterior draws (after burn-in and thinning) at the specified depths.
2. Get the complete set of posterior draws for the parameters in the model.

Thanks!

**Comment by wetlandscapes** [comment]
I see now that I can use the `ageof` function to get the posteriors for a given depth value.
I'm guessing that some of the other results are in the model outputs, but it's not entirely clear as to what these outputs mean. So, I think just including some additional documentation related to this package would be really helpful.

**Comment by maquinolopez** [comment]
Thank you for the interest in Plum. 

- As you found the function -ageof()- will give you the ages obtained from each iteration and a plot of the density of the age at a given depth. 
- About additional documentation, we are working on a more complete package which will be fully documented, and should work on windows without the need for using WSL.

Any more comments let me know
